import QtQuick
import Quickshell
import Quickshell.Io

Scope {
    id: global

    // Track if notification has already been shown
    property bool themeNotificationShown: false

    // Function to show notification once
    function notifyPredefinedTheme() {
        if (!themeNotificationShown) {
            themeNotificationShown = true
            Quickshell.execDetached([
                "notify-send",
                "Nucleus Shell",
                `You are using a predefined theme ${Config.runtime.appearance.colors.scheme}. Color generation/Light Theme is not supported for this theme.`,
                "--urgency=normal",
                "--expire-time=5000"
            ])
        }
    }

    // Handle Global IPCs
    IpcHandler {
        target: "global"

        function toggleTheme() {
            // Get the current theme
            const currentTheme = Config.runtime.appearance.theme
            const newTheme = currentTheme === "light" ? "dark" : "light"

            Config.updateKey("appearance.theme", newTheme)

            // Run color generation if allowed
            if (Config.runtime.appearance.colors.autogenerated) {
                genThemeColors.running = true
            } else {
                notifyPredefinedTheme()
            }
        }

        function regenColors() {
            if (Config.runtime.appearance.colors.autogenerated) {
                genThemeColors.running = true
            } else {
                notifyPredefinedTheme()
            }
        }
    }

    // Process to generate colors
    Process {
        id: genThemeColors

        command: [
            "bash",
            Directories.scriptsPath + "/interface/gencolors.sh",
            Config.runtime.appearance.background.path,
            Config.runtime.appearance.colors.matugenScheme,
            Config.runtime.appearance.theme,
            Quickshell.shellPath("extras/matugen/config.toml")
        ]
    }

}
