name: Issue # Note: I've copied this template from github.com/end-4/dots-hyprland
description: for reporting any issue
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "**Welcome to submit a new issue!**\n- Please search in [existing issues](https://github.com/xZepyx/aelyx-shell/issues?q=is%3Aissue) before continue.\n- It takes only 3 steps, so please be patient :)\n- NOTE 1: If your issue is not a feature request, and it does not fit into the following form, for example \"how can I edit some widget\", please use [Discussions](https://github.com/xZepyx/aelyx-shell/discussions) instead.\n- NOTE 2: If your problem is distro specific and you do not use Arch(-based) distros, please submit [Discussion at Extra Distros](https://github.com/xZepyx/aelyx-shell/discussions/new?category=extra-distros) instead."
  - type: checkboxes
    attributes:
      label: "Step 1. Before you submit"
      description: "Hint: The 2nd and 3rd checkbox is **not** forcely required as you may have failed to do so."
      options:
        - label: I've read the troubleshooting steps from the README.
          required: true
        - label: I've successfully updated to the latest version of aelyx-shell.
          required: false # Not required cuz user may have failed to do so
        - label: I've successfully updated the system packages to the latest.
          required: false # Not required cuz user may have failed to do so
        - label: I am not using a alpha/beta/rc build.
          required: false # Obviously
  # TODO: Use GitHub Action to auto add folding tag if the log contains more than 15 lines, instead of tell user to "paste here" cuz many users actually does not know its meaning (It's also not convenient anyway).
  - type: textarea
    attributes:
      label: "Step 2. Quick diagnose info"
      description: "Run `quickshell -c ae-qs` after killing quickshell, and paste the result below."
      value: "<details><summary>Quick diagnose</summary>\n\n```\n<!-- Run `quickshell -c ae-qs` after killing quickshell, and paste the result here! -->\n```\n\n</details>"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Tips for the following Step 3**
        1. Use `LANG=C LC_ALL=C` to get the output of a command in English, eg. `LANG=C LC_ALL=C date` displays time in English.
        2. If it throws errors, **PLEASE**, attach logs and describe in detail if possible.
           - Bar and widgets not showing? run `pkill quickshell; quickshell -c ae-qs` for logs.
           - Installation failed? Run installation again for logs.
           - You may use more code blocks when needed.
        3. In case you are confused, the `<details>`, `<summary>`, `</summary>`, `</details>` are HTML tags for folding the logs (typically very long) inside. Please do not touch them (unless you know what you are doing).
        4. If the logs are suuuuuuper long, consider using an online pastebin service instead.

  - type: textarea
    attributes:
      label: "Step 3. Describe the issue"
      value: "\n<!-- Firsly describe your issue here! -->\n\n<details><summary>Logs</summary>\n\n```\n<!-- Put your log content here!-->\n```\n\n</details>"
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Reminder
      options:
        - label: I agree that it's usually impossible for others to help me without my logs.
          required: true
