name: "Bug Report"
description: "Report a bug in Aelyx-Shell"
title: "[BUG]"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.
  - type: input
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the bug"
      placeholder: "1. ...\n2. ...\n3. ..."
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "What did you expect to happen?"
  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "OS, Shell Version, Dependencies, etc."
      placeholder: "e.g., Arch Linux, Aelyx-Shell v1.2.3"
