name: "Feature Request"
description: "Suggest a new feature or improvement for Aelyx-Shell"
title: "[FEATURE]"
labels: ["enhancement"]
assignees: []

body:
  - type: input
    id: feature
    attributes:
      label: "Feature Description"
      description: "Describe the feature or improvement you want"
      placeholder: "..."
  - type: textarea
    id: benefit
    attributes:
      label: "Benefit"
      description: "How would this feature help?"
  - type: input
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Any alternative solutions?"
