name: "Installation Verification"
description: "Checklist to ensure correct installation of Aelyx-Shell"
title: "[INSTALL CHECK]"
labels: ["checklist", "installation"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Before submitting an issue, please confirm the following:

  - type: checkboxes
    id: install_checklist
    attributes:
      label: "Installation Checklist"
      options:
        - The install script completed without errors, and I did not skip or ignore any failed commands
        - My system is up to date (including Aelyx-Shell)
        - I am using the latest stable release of Aelyx-Shell (not beta/alpha/rc build)
